version: 2
updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
      angular:
        patterns:
          - "@angular/*"
          - "zone.js"
      ag-grid:
        patterns:
          - "ag-grid-*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
